build:	
	g++ -std=c++17 -o walsh walsh.cpp
	g++ -std=c++17 -o statistics statistics.cpp
	g++ -std=c++17 -o prinel prinel.cpp
	g++ -std=c++17 -o crypto crypto.cpp
	g++ -std=c++17 -o regele regele.cpp
run-p1:	
	./walsh
run-p2: 
	./statistics
run-p3: 
	./prinel
run-p4: 
	./crypto
run-p5: 
	./regele
clean:	
	rm walsh statistics prinel crypto regele
